### PR TITLE
bug/VCMS74

### LINKED ISSUE #74: [Service Module] Unable to refresh the Datagrid after Searching a Service record.
There's an issue encountered during searching a service record.

Branch: int/INT_2024_11
DB: vcms.sql (October 30)

See data in the service record for reference.
image

Steps to recreate:
1. Search "MED", result will be displayed in the datagrid. 
2. However, if you search "VAX", records will not shown in the datagrid.

Additionally,
- After clearing the value in the search field, service records in the datagrid should be (refreshed) populated again.

### PR DESCRIPTION
**Pull request by lhyra13**

### CODE REVIEW

File: app/View/Services/frmServices.cs [hunk 1]
```diff
@@ -32,18 +32,29 @@ private void frmServices_Load(object sender, EventArgs e)
...
+
                 ServiceRepository repository = new ServiceRepository();
-                dgvServices.DataSource = repository.SearchService(txtSearch.Text);
+                dgvServices.DataSource = repository.SearchService(txtSearch.Text.Trim());
                 this.dgvServices.Columns["Id"].Visible = false;
             }
             else
             {
-                MessageBox.Show("The search field is empty, please provide.", "Empty field", MessageBoxButtons.OK, MessageBoxIcon.Information);
+                RefreshDataGridView();
```
Comment (blackMisay) [inline app/View/Services/frmServices.cs:42]: kindly retain the message dialog to inform user that the search text field is empty.

File: app/View/Services/frmServices.cs [hunk 2]
```diff
@@ -32,18 +32,29 @@ private void frmServices_Load(object sender, EventArgs e)
...
             }
+
         }
+            private void RefreshDataGridView()
+            {
+                UpgradeFile upgradeFile = new UpgradeFile();
+
+                dgvServices.DataSource = upgradeFile.Load("SELECT * FROM services WHERE isDeleted = 0");
+                dgvServices.Refresh();
```
Comment (blackMisay) [inline app/View/Services/frmServices.cs]: No need to call the Refresh method since the data loaded in the DataGridView is not a bindingsource type.

File: app/View/Services/frmServices.cs [hunk 3]
```diff
@@ -32,18 +32,29 @@ private void frmServices_Load(object sender, EventArgs e)
...
                 this.dgvServices.Columns["Id"].Visible = false;
             }
             else
             {
-                MessageBox.Show("The search field is empty, please provide.", "Empty field", MessageBoxButtons.OK, MessageBoxIcon.Information);
+                RefreshDataGridView();
             }
+
         }
+            private void RefreshDataGridView()
```
Comment (blackMisay) [inline app/View/Services/frmServices.cs:46]: Use this method in the Form_Load event, for code reusability.

**Review by blackMisay — CHANGES_REQUESTED** [review]
Hi @lhyra13, kindly check my review points thanks.

**Review by blackMisay — APPROVED** [review]
Hi @lhyra13. approved. **Squash your commits** into one then you can proceed on merging. Thanks
