### PR TITLE
bug/VCMS75

### LINKED ISSUE #75: [Service Module] Able to Create/Update duplicate service code.
An issue was encountered during create/update of service record.

Branch: int/INT_2024_11
DB: vcms.sql (October 30)

The user was able to create or update a service record using the same Service Code, which should not occur, as the Service Code is a unique identifier for each service record.

Resolution:
- Enable the program to validate the provided service code during Create/Update of a service record.

### PR DESCRIPTION
**Pull request by lhyra13**
included the issue in [Service Module] Able to create negative amount in service price #73 .

### CODE REVIEW

File: app/Core/Repository/ServiceRepository.cs [hunk 1]
```diff
@@ -86,6 +86,76 @@ public Services GetService(Services service)
             return null;
         }
 
+        public bool IsDuplicateServiceCode(string serviceCode)
+        {
+            string query = "SELECT COUNT(*) FROM services WHERE serviceCode = @ServiceCode AND isDeleted = 0";
```
Comment (blackMisay) [inline app/Core/Repository/ServiceRepository.cs]: Hi @lhyra13, based on the query - we are checking duplicate non-deleted service code in the service database. But how about those deleted service code? 

If the scenario is:

We have an existing Service Code = TEST but has isDeleted=1.
Then we add another Service Code with the same value as TEST but has isDeleted=0.
- Will this be called duplicate or not? 
- Should the client need to recreate a new code even it is already existed or should they set the deleted one to active to be use again?

File: app/Core/Repository/UpgradeFile.cs [hunk 2]
```diff
@@ -219,5 +219,73 @@ public List<KeyValuePair<int, string>> Populate(string query, Dictionary<string,
             }
             finally { this.connection.Close(); }
         }
+
+        public int ExecuteQuery(string query, Dictionary<string, object> parameters)
```
Comment (blackMisay) [inline app/Core/Repository/UpgradeFile.cs]: Redundant code, similar with the existing method in line 77

File: app/Core/Repository/UpgradeFile.cs [hunk 3]
```diff
@@ -219,5 +219,73 @@ public List<KeyValuePair<int, string>> Populate(string query, Dictionary<string,
...
+            {
+                throw new Exception($"Unexpected error: {e.Message}");
+            }
+            finally
+            {
+                this.connection.Close(); // Ensure the connection is closed
+            }
+        }
+
+        public int ExecuteScalar(string query, Dictionary<string, object> parameters)
```
Comment (blackMisay) [inline app/Core/Repository/UpgradeFile.cs]: Redundant code, you can improve the existing method in line 77, if you want to return the scalar method of the query

File: app/Core/Repository/ServiceRepository.cs [hunk 4]
```diff
@@ -86,6 +86,76 @@ public Services GetService(Services service)
...
+
+            UpgradeFile upgradeFile = new UpgradeFile();
+
+
+            int rowsAffected = upgradeFile.ExecuteScalar(query, parameters);
+
+            return rowsAffected > 0;
+        }
+
+        public bool UpdateService(app.core.model.Services service)
```
Comment (blackMisay) [inline app/Core/Repository/ServiceRepository.cs]: Redundant code, improve the existing SaveService method to accommodate the INSERT/UPDATE action of the Service module. See other reference from different modules.

File: app/Core/Repository/ServiceRepository.cs [hunk 5]
```diff
@@ -86,6 +86,76 @@ public Services GetService(Services service)
...
+            UpgradeFile upgradeFile = new UpgradeFile();
+
+
+            int count = upgradeFile.ExecuteScalar(query, parameters);
+
+            return count > 0;
+        }
+
+
+        public bool UpdateServicePrice(string serviceCode, decimal newPrice)
```
Comment (blackMisay) [inline app/Core/Repository/ServiceRepository.cs]: Does this method still needed, I don't see any code or block that reference in this method. Remove it if it has no use.

**Review by blackMisay — CHANGES_REQUESTED** [review]
Hi @lhyra13, kindly review my changes.

File: app/Core/Repository/ServiceRepository.cs (hunk 1 above)
Comment (lhyra13) [reply app/Core/Repository/ServiceRepository.cs]: If there is an existing service code marked as isDeleted = 1 and you attempt to add a new service with the same code but with isDeleted = 0, it will not be treated as a duplicate based on the IsDuplicateServiceCode logic. but we must also recreate the service code or reactivate the deleted one depending on the business rules. 

 If the existing code (with isDeleted = 1) should be used again, how can we set isDeleted = 0 to reactivate it?

Comment (blackMisay) [reply app/Core/Repository/ServiceRepository.cs]: Hi @lhyra13, kindly check issues I encountered during my review.

1. **Saving new service record.**

    **UI Form (frmServicesModal.cs)**
    image

    **DB (vcms.services)**
    image

    **Issue:** Provided ServiceCode=SERVICECODE1 is not yet existed in services table, but the program tells that it is already existed.

4. **Update**
Updating the service code of a record doesn't reflect into the database. Also there's no checking if the updated service code is already used by other record. It should also have that kind of validation here in UPDATE action.
5. **Field validation**
I can enter a whitespace Service code, description, and price.
image
**NOTE**: The `Price` field with value `1` in the image, has a `space` character before the numeric value `1`. I actually enter it like this ` 1`. 

**Another added consideration**
- Sort your services to the most recent records when loading it into datagridview.

**Regarding on your question:**
- **Q**: _If the existing code (with isDeleted = 1) should be used again, how can we set isDeleted = 0 to reactivate it?_
- **A**: Instead of `isDeleted`, we can implement a Status dropdown with value 'Active','Inactive' in the service record. Similar to what I implemented in the Account Module for User records. Additionally, if this will be the new approach we should also change the behavior of the `Remove` to set the selected record as 'Inactive' to remove.

**Review by blackMisay — CHANGES_REQUESTED** [review]
Hi @lhyra13, kindly check

**Review by blackMisay — CHANGES_REQUESTED** [review]
Hi here's my review:
- Confirmation if we should allow duplicates for Inactive servicecode.
- **During UPDATE:**
> Validation for duplicate works but the actual update did not.
> Update is not working in the ServiceCode field but it is working for Description and Amount.
- **During INSERT:**
> Datagridview is not refreshing automatically after saving

Minor:
- I am allowed to input and save amount with spaces. But it is being fixed by the code by removing trail spaces correctly .

File: app/Core/Repository/ServiceRepository.cs (hunk 1 above)
Comment (lhyra13) [reply app/Core/Repository/ServiceRepository.cs]: done with this issue , please review my changes . thank you 


I update my database , I add constraints in adding negative value in price.

ALTER TABLE services
ADD CONSTRAINT CHK_Price_NonNegative
CHECK (Price >= 0);

File: app/View/Services/frmServicesModal.cs [hunk 6]
```diff
@@ -31,26 +29,88 @@ private void FrmServicesModal_Load(object sender, EventArgs e)
...
+                    return;
+                }
+
+                // Save or update the service
+                bool success = serviceRepository.SaveService(service);
+                if (success)
+                {
+                    MessageBox.Show(service.Id == 0 ? "Saved successfully." : "Service updated successfully.");
+
+                    LoadServiceDetails();
```
Comment (blackMisay) [inline app/View/Services/frmServicesModal.cs]: During adding new service record, this code block will throw an error due to the default value of `Id`=0.
image

I believe this method `LoadServiceDetails()` is only used to fetch and populate the fields in the ServiceModal during update.

I don't see any significance why do we need to call it here, since the record was already added/updated in any case.

```suggestion
        // Remove the code including LoadServiceDetails(); in Line 96 to 97.
```

File: app/Core/Repository/ServiceRepository.cs [hunk 7]
```diff
@@ -22,45 +21,69 @@ public DataTable SearchService(string searchValue)
...
+            Dictionary<string, string> parameters;
 
-            bool saveState = services.Id > 0 ? true : false;
+            // Determine if we're updating an existing service or inserting a new one
+            bool saveState = service.Id > 0;
 
             if (saveState)
             {
-                sql = "UPDATE services SET id=@Id WHERE id=@Id;";
+                // Update existing service
```
Comment (blackMisay) [inline app/Core/Repository/ServiceRepository.cs:34]: ServiceCode still not yet reflecting after updating.

**Before:**
image

**After:**
image

RESULT:
image

**Review by blackMisay — CHANGES_REQUESTED** [review]
Kindly check the issues encountered thanks

**Review by blackMisay — APPROVED** [review]
